### ISSUE TITLE
Unable to Fetch Document - Error Code 500

### ISSUE THREAD

**Issue by jacquetwong** [brainly/nodejs-onesky-utils#62]
### Bug Description
When running the provided test script (`api-test.js`) to fetch a document using the `@brainly/onesky-utils` package, an error occurs with the message "Unable to fetch document" and an error code of 500.

### Steps to Reproduce
1. Save the code as `api-test.js`:

```javascript
var onesky = require('@brainly/onesky-utils');

var options = {
  language: 'en',
  secret: 'YOUR_SECRET',
  apiKey: 'YOUR_API_KEY',
  projectId: 'YOUR_PROJECT_ID',
  fileName: 'YOUR_FILE_NAME (e.g. en.yml)',
  format: 'YOUR_FILE_FORMAT (e.g. RUBY_YAML)'
};

onesky.getFile(options)
  .then(function(content) {
    console.log(content);
  })
  .catch(function(error) {
    console.log(error);
  });
```

2. Install packages:
```npm i @brainly/onesky-utils```

3. Run the test:
```node api-test.js```

### Expected Result
The test should return a status code in the 2xx range and provide the contents of the translation file.

### Actual Result
Instead, the test throws an error with the following message and error code:
```{ message: 'Unable to fetch document', code: 500 }```

**Comment by jacquetwong** [comment]
### Workaround
By trimming the trailing slash from the base API URL (https://github.com/brainly/nodejs-onesky-utils/blob/master/lib/globals.js#L5), the issue can be resolved successfully. Here are the steps to implement the workaround:

1. Open the `globals.js` file in the `nodejs-onesky-utils` repository
2. Locate line 5 of the file, which contains the base API URL in the variable named `apiAddress`
3. Modify the URL from `https://platform.api.onesky.io/` to `https://platform.api.onesky.io` (remove the trailing slash).

By making this adjustment, the issue should be resolved, and the API calls should work as expected.

**Comment by trioni** [comment]
Also experiencing the same issue. With the double `//` the call fails with a `404` `text/html` response, which internally is mapped to the `500` output:

```js
{ message: 'Unable to fetch document', code: 500 }
```

I saw this PR from last fall that is regarding the same issue https://github.com/brainly/nodejs-onesky-utils/pull/55

**Comment by krzotki** [comment]
Issue fixed in: https://www.npmjs.com/package/@brainly/onesky-utils/v/1.4.2
Closing

**Comment by tlkiong** [comment]
I am still facing this issue even on https://www.npmjs.com/package/@brainly/onesky-utils/v/1.4.2.
🤔
